---
name: 'CSA: Out of Office Form'
about: 'Let your account teams and manager know about upcoming time off'
title: 'OOO: [GITHUB_HANDLE] from [DD-MMM-YYYY] to [DD-MMM-YYYY]'
labels: OOO

---

<!--
Please use the title format in this template and add specifics to the body.
-->

## ✅ Approval

- [ ] @[MANAGER]’s :+1:

## 📅 OOO Dates

**Select your OOO start and end dates:**

Start Date: 
  - type: date
    id: start_date
    attributes:
      required: true

End Date: 
  - type: date
    id: end_date
    attributes:
      required: true

## 📋 How are your responsibilities being covered?

**OBD's/Customers:**

- Do you require a backup while you are out? Are there any customer engagements/OBD's that need to be covered by another CSA?

  - type: textarea
    id: obds_customers
    attributes:
      label: 'OBD’s/Customers:'
      description: 'Enter any details about customer engagements or OBDs that need to be covered.'

## 📣 Informed

**GitHub Internal Awareness:**

_Note: @MENTION (anyone who should know you are out CSM, AM, SE, etc.)_

  - type: textarea
    id: informed
    attributes:
      label: 'GitHub Internal Awareness:'
      description: 'Mention any team members who should be informed of your OOO.'

## 👤 Manager

**Select your manager from the list:**

  - type: dropdown
    id: manager
    attributes:
      label: 'Manager'
      options:
        - '@manager1'
        - '@manager2'
        - '@manager3'

## 👣 Next steps

**Before OOO time:**

- [ ] ⛑ Workday OOO request (only non-:us: Hubbers) opened
- [ ] 📧 [Email auto-responder set](https://support.google.com/mail/answer/25922)
- [ ] 📅 Google Calendar set to OOO time ([auto-declines](https://support.google.com/calendar/answer/7638168))
- [ ] 📅 Recurring calendar events/meetings declined during OOO period

**At start of OOO time:**

- [ ] 💬 Slack OOO message set
- [ ] 👤 GitHub Profile status set (optional)

**At end of OOO time:**

- [ ] 💬 Slack OOO message cleared
- [ ] 📧 Email auto-responder cleared (or auto-expired)
- [ ] 👤 GitHub Profile status cleared (optional)

---

<sup>**Please note:** this issue was created from [csa--out-of-office](https://github.com/github/customer-success-architects/blob/main/.github/ISSUE_TEMPLATE/csa--out-of-office.md). PRs to update @mentioned teams, individuals, checklists items, etc. are welcome.</sup>
