name: Sync OOO to Google Calendar
on:
    issues:
        types: [opened, edited, deleted]
permissions:
  contents: read

jobs:
  update_gcal:
    name: Sync CSA Global PTO
    if: contains(github.event.issue.labels.*.name, 'OOO')
    uses: cheeragpatel-test/gcal-sync-workflow/.github/workflows/ooo.yaml@auth-refactor
    with:
        GOOGLE_CALENDAR_ID: ${{ vars.GOOGLE_CALENDAR_ID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_ACTION: ${{ github.event.action }}
        GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
    secrets:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
