name: Create Sub Issues from Tasklist
on:
  issues:
    types: [opened, edited]

jobs:
  create-sub-issues:
    runs-on: ubuntu-latest
    if: contains( toJSON(github.event.issue.labels) , 'CS-Release-Readiness')
    steps:
      - name: Create linked sub-issues from tasklist
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const issueBody = context.payload.issue.body
            const parentIssueNumber = context.payload.issue.number

            // Extract the content between ```[tasklist] and ```
            const matchTasklist = issueBody.match(/```\[tasklist\]([\s\S]*?)```/)
            if (!matchTasklist) {
              core.info('No [tasklist] section found in the issue body.')
              return
            }

            const tasklistContent = matchTasklist[1]
            // Identify lines that match '- [ ] ...'
            const tasks = tasklistContent.match(/^- \[ \] .+/gm) || []

            for (const task of tasks) {
              const title = task.replace(/^- \[ \] /, '').trim()
              const newIssue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: `Sub-issue of #${parentIssueNumber}`
              })

              // Link the sub issue to the parent issue
              await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/sub_issues', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parentIssueNumber,
                sub_issue_id: newIssue.data.id
              })

               // Comment on the parent issue linking the new sub-issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parentIssueNumber,
                body: `Created sub-issue: #${newIssue.data.number} for task: "${title}"`
              })             
            }
